[theme]
primaryColor = "#1033CF"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F8"
textColor = "#010504"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
